### ISSUE TITLE
Bug? Recaptcha styling 

### ISSUE THREAD

**Issue by evertalbers** [bolt/boltforms#103]
I tried changing the recaptcha the to fit the dark background on the footer in http://c-ior.nl

Using _blackglass_ mentioned in https://doc.osclass.org/Customizing_the_theme_and_language_of_reCAPTCHA

```
recaptcha:
  enabled: true
  (...)
  theme: "blackglass"
```
But it still looks like he picks the white theme.

Bolt 2.2.23, Boltforms v2.5.2
