### ISSUE TITLE
fields not being translated after setup

### ISSUE THREAD

**Issue by Puddingboy** [bolt/boltforms#105]
bolt 3.x and boltforms+translate fresh install

During my setup I first added
```
locales:
    nl_NL:
        label: Nederlands
        slug: nl
    en_GB:
        label: English
        slug: en
    de_AT:
        label: Deutsch
        slug: de
```

Only after updating the db I changed my default locale to nl_NL

currently no field is being translated and no db update is being offered. looking for suggestions to fix this.

`is_translateable: true` does not fix it. Can only reinstalling the plugin fix this?
