### ISSUE TITLE
Cache request

### ISSUE THREAD

**Issue by nlemoine** [bolt/boltforms#108]
With cache request set to `true`, after submitting a form and when I load it again, the page keeps showing the feedback message. 

Only GET request should be cached? Is there a way to disable cache for certain pages?

**Comment by GawainLynch** [comment]
Do you mean the Bolt setting for request caching?

**Comment by nlemoine** [comment]
Yes, sorry forgot to mention. 

```yaml
caching:
    config: true
    templates: true
    request: true
    duration: 10
    authenticated: false
    thumbnails: true
    translations: true
```
