### ISSUE TITLE
error when email template rendering encounters arrays

### ISSUE THREAD

**Issue by jadwigo** [bolt/boltforms#124]
If you have a bolform with a multiple select checkbox the form does not save the data because the email template rendering throws an error.

```yml
    clientcategories:
      type: choice
      options:
        required: false
        expanded: true
        multiple: true
        label: Which categories are you entering?
        choices:
          app: App
          website: Website
          interactive: 'Games & Interactive experiences'
          film: 'Film & Video'
        attr:
            class: categoryinputsource
```

The twig renderer complains about invalid json - which is correct becasue the form returns an array:

```
Uncaught Exception: Twig_Error_Runtime

Twig_Error_Runtime in Template.php line 443: 
An exception has been thrown during the rendering of a template ("Warning: json_decode() expects parameter 1 to be string, array given") in "forms/[**clientname removed**]_email.twig" at line 15.
```

The array is somewhere down in the FormData for the field `clientcategories` in : `Bolt\Extension\Bolt\BoltForms\Submission\Handler\Email::compose(FormConfig, EmailConfig, FormData,  MetaData)`

![image](https://cloud.githubusercontent.com/assets/1488214/20677070/350f5ac2-b592-11e6-8e9e-9e08f7579eb9.png)
