### ISSUE TITLE
[BUG] Upon form submission, exception occurs

### ISSUE THREAD

**Issue by Maelstromeous** [bolt/boltforms#132]
Upon submitting my form, I'm getting the following exception:

```
Twig_Error_Runtime in Template.php line 222: 
An exception has been thrown during the rendering of a template ("Warning: file_get_contents(): php_network_getaddresses: getaddrinfo failed: Name or service not known") in "register.twig" at line 9.
```

On line 9, it's simply just the twig call I make to render the form within my template: `{{ boltforms('register') }}`

Config:

```
register:
    fields:
        name:
            required: true
            type: text
            options:
                label: Name
        email:
            required: true
            type: email
            options:
                label: Email
        submit:
            type: submit
            options:
                label: Subscribe
    notification:
        enabled: true
        subject: New registiration
        from_name: Testing
        from_email: matt.cavanagh@barnsley-chronicle.co.uk
        to_name: Matt Cavanagh
        to_email: matt.cavanagh@barnsley-chronicle.co.uk
```

Full stack trace:
![uncaught exception twig_error_runtime](https://cloud.githubusercontent.com/assets/1776058/21011925/73a8cc30-bd4b-11e6-9c6f-e5aa8ce6e594.png)
