### ISSUE TITLE
[feature request] Allow population of relations via form fields

### ISSUE THREAD

**Issue by davejtoews** [bolt/boltforms#139]
I asked about this on Slack and was encouraged to submit an issue.

I'd find it useful to have a way to create relations via form submission. I can create a dropdown selector of content items in the form, but I can't directly allow that field to define a relation. [See example code in this StackOverflow question.](http://stackoverflow.com/questions/42237319/in-bolt-cms-is-it-possible-to-populate-relationships-when-creating-content-with)

**Comment by rossriley** [comment]
OK, this fix is now merged.

With the latest from the 3.3 branch you can do this setup in a bolt form.

```yaml
        pages:
            type: choice
            options:
                required: false
                label: Choose Related Pages
                choices: { 'Page 1': 1, 'Page 2': 2 }
                multiple: true
        categories:
            type: choice
            options:
                required: false
                label: Choose Category
                choices: { 'News': news, 'Events': events, 'Movies': movies, 'Music': music }
```

and assuming those relations and taxonomies are setup on your destination contenttype then they will be saved against the new record.
