### ISSUE TITLE
type: choice shows id, not nice names

### ISSUE THREAD

**Issue by melcarthus** [bolt/boltforms#145]
```yml
    needreply:
      type: choice
      options:
        required: false
        label: Wilt u een terugbel afspraak maken?
        choices: [ Ja, Nee ]
        multiple: false
```
Instead of showing Ja, or Nee it shows either, 1 or 2.

**Comment by jadwigo** [comment]
If you use a slighly different definition it will work the way you expect:
```yml
    needreply:
      type: choice
      options:
        required: false
        label: Wilt u een terugbel afspraak maken?
        choices: 
            Ja: Ja
            Nee: Nee
        multiple: false
```
