### ISSUE TITLE
Can't deliver email when mailoption spool option true

### ISSUE THREAD

**Issue by everyx** [bolt/boltforms#150]
in `config.yml`;

```yml
mailoptions:
    transport: smtp
    spool: true
    host: smtp.xxxxxx.com
    port: 25
    encryption: false
    username: xxxxx@xxxxx.com
    password: xxxxxxxx
    senderMail: xxxxx@xxxxx.com
    senderName: noreply
```
but when I disable `mailoptions` pool, and I can get the notification email.

Version: Bolt 3.2.10 & BoltForms 3.1.0
