### ISSUE TITLE
[Feature Request] More spam prevention options

### ISSUE THREAD

**Issue by benwallis** [bolt/boltforms#151]
CAPTCHA can be overkill sometimes.

Could there be an option to enable a "honeypot" form field?
And also an option to set a certain number of seconds that need to pass before the form can be submitted?

There's a Symfony bundle that works well (it does both honeypot and timed prevention)

https://packagist.org/packages/isometriks/spam-bundle

**Comment by deranku** [comment]
I created a simple honeypot filed like this:
```
honigtopf:
  type: checkbox
  options:
    label: false
    required: false
    attr:
      value: "honigtopf"
      class: honigtopf
    constraints: [ IsFalse ]
```
As you can see, I avoided the word "honeypot", don't know if that is already too much caution  =)
Don't forget to set the field to `display: none;` in your CSS.
