### ISSUE TITLE
[Feature request] Numeric field constraints example in showcase

### ISSUE THREAD

**Issue by sbonardt** [bolt/boltforms#152]
Hi,

I wanted to add a numeric type field to my form and found out it wasn't that easy for me to do. I searched through the Symfony docs but couldn't find the right way. After some help we found out this way of adding the constraint to a text field:

```
housenumber:
      type: text
      options:
        required: true
        label: Huisnummer
        attr:
          placeholder: Huisnummer
          class: half
        constraints: [ NotBlank, {Type: {type: integer }}, {Range: {min: 1, max: 20000 }} ]
```

It would be nice to see this back in the docs of boltforms or at least as an example in boltform.bolt.yml in the showcase form. It could speed up the adoption and usage of boltforms and give a better user experience for front-end devs building a form who are not skilled in understanding Symfony code explanations

Something like:

```
number:
      type: text
      options:
        required: true
        label: Number
        constraints: [ NotBlank, {Type: {type: integer }}, {Range: {min: 1, max: 20000 }} ]
```

Oh, and then probably add an example of a checkbox field as well, as this seems to be missing in the docs also:

```
checkbox:
      type: choice
      options:
        required: true
        label: Checkbox label
        choices: {  'ja' : "yes" }
        multiple: true
        expanded: true
        constraints: [ NotBlank ]
```
