### ISSUE TITLE
v4.0 beta 2 does not do file submission correctly

### ISSUE THREAD

**Issue by Puddingboy** [bolt/boltforms#153]
The submitted file only contains the prefix as a name and no further data.
In boltforms v3.1.0 files still get send correctly.
I am using bolt 3.2.14 with bolt translate 4.0.7.
I used blanc templates with no adjustments for later tests and the issue remained.

My boltforms.yml:

```
uploads:
  enabled: false                               # The global on/off switch for upload handling
  base_directory: /full/path/for/uploaded/files/ # Outside web root and writable by the web server's user
  filename_handling: suffix                      # Can be either "prefix", "suffix", or "keep"
  management_controller: false                   # Enable a controller to handle browsing and downloading of uploaded files
```

my form:
```
formname:
  notification:
    enabled: true
    debug: false
    attach_files: true
```

on field:
```
some_file:
      type: file
      options:
        label: some_file
        required: true
```

mailsettings:
```
mailoptions:
    transport: smtp
    spool: true
    host: localhost
    port: 25
```

php version: 5.5.9-1ubuntu4.14
submitted to gmail for testing < nothing ended up in the spamfolder
showing the original message did nothing for the file

The mail shows that a file is attached with a name like `phpwHN5Ue`
the file has no preview to how what kind of file it is.
I know for a fact that the file should be viewable because I sent a test.jpeg file.

Let me know what other data you need. Within reason i'll try to submit as much as you need.
