### ISSUE TITLE
[BoltForms 4] System Log flood

### ISSUE THREAD

**Issue by xiaohutai** [bolt/boltforms#156]
Everytime I submit the form, I get one or two entries in the System Log:

```
[BoltForms]: An event dispatcher encountered an exception. 
```

It points to this line: https://github.com/bolt/boltforms/blob/4.0/src/Submission/Processor/Redirect.php#L87

I suppose the handler before it `$handler->refresh($request);` should actually return a Response; but I'm not even sure about that 😋 

### Reproduction:

- Installed Bolt 3.3 (in particular `-beta13`, but issue also happens on `3.2.14`)
- Set `minimum-stability` to `dev` in `config.yml`
- Installed `bolt/boltforms 4.0.0-beta2 `
- `{{ boltforms('contact') }}` in `index.twig`
- Submit the form on the homepage

**Comment by tompato** [comment]
@rossriley - config you asked for on Slack

```yaml
contact:
    submission:
        ajax: false
    notification:
        enabled: true
        subject: New contact message submitted
        from_name: Example Website
        from_email: contact@example.com
        replyto_email: email
        replyto_name: name
        to_name: Someone
        to_email: someone@example.com
    feedback:
        success: Message submission successful
        error: There are errors in the form, please fix before trying to resubmit
        redirect:
          target: /thank-you-contact
    database:
        contenttype: messages
    fields:
        name:
            type: text
            options:
                required: true
                label: Name
                attr:
                    placeholder: Your name...
                constraints: [ NotBlank, { Length: { 'min': 3, 'max': 128 } } ]
        email:
            type: email
            options:
                required: true
                label: Email address
                attr:
                    placeholder: Your email...
                constraints: [ NotBlank, Email ]
        message:
            type: textarea
            options:
                required: true
                label: Your message
                attr:
                    placeholder: Your message...
                    class: myclass
        submit:
            type: submit
            options:
                label: Submit my message »
                attr:
                    class: button primary
```
