### ISSUE TITLE
Provide documentation/example on setting default value for SELECT drop down field

### ISSUE THREAD

**Issue by jamieburchell** [bolt/boltforms#157]
I've searched the Bolt Forms docs and Symphony docs but can't find nor fathom how to simply set a default value for a select field in the config for a form. Is it even possible?

I tried "value", "data" and (all?) of the other properties mentioned that seemed related in the Symphony docs.

Also tried preferred_choices property and that doesn't seem to do anything.

For context, I'm using a "country" field type and was trying to set a default or rearrange the options.

Also according to Symphony docs it should be possible to pass an array to the placeholder property to set a placeholder on the day/month/year fields, but this does not seem to do anything?

So yeah, some examples or documentation would be useful.

Using Boltforms 4 and Bolt 3.2.13

**Comment by rossriley** [comment]
Here's how to do it:

```yml
location:
            type: country
            options:
                label: Where are you From?
                data: GB
```

I'll add to the docs too.
