### ISSUE TITLE
[BUG] [BoltForms 4] Saving to content type not working properly

### ISSUE THREAD

**Issue by pcmdev** [bolt/boltforms#170]
When saving a form to a content type the content type is saved correctly but two things happen:

- The content type is always set as published, no matter what default status is set on the contenttypes.yml file.
- If notifications are enabled the following error is thrown:

```
 Twig_Error_Runtime in Template.php line 230:
An exception has been thrown during the rendering of a template ("Bolt\Extension\Bolt\BoltForms\Config\Form\FieldOptionsBag ") in "@BoltForms/email/_blocks.twig" at line 4. 
```

Details
-------

 - Relevant Bolt Version: [ 3.3 ]
 - Install type: [ Composer install ]
 - PHP version: [ 7.0 ]
 - Used web server: [ Apache ]

**Comment by jadwigo** [comment]
If you want to save an item as draft (or similar) you can add a hidden field to your configuration for the status:

```yml
        status:
            type: hidden
            options:
                label: false
                attr:
                    value: draft
```
