### ISSUE TITLE
[BUG] [Boltforms 4] Undefined variable 'Legacy' on select with contenttypes

### ISSUE THREAD

**Issue by melcarthus** [bolt/boltforms#171]
**Bolt/Extensions**

Bolt 3.3.1

```json
        "animal/translate": "^4.0",
        "bacboslab/menueditor": "^3.2",
        "bobdenotter/seo": "^1.0",
        "bolt/boltforms": "^4.1",
        "bolt/labels": "^3.0",
        "bolt/sitemap": "^2.2"
```

**Description** 

When I add a choice to a form with content-type values I get an error (view below).

**Uncaught Exception: Twig_Error_Runtime.**

```
Twig_Error_Runtime in Template.php line 447: 
An exception has been thrown during the rendering of a template ("Notice: Undefined variable: legacy") in "templates-parts/_booking.twig" at line 4.
```

```php
                $e->guess();
            }

            throw $e;
        } catch (Exception $e) {
            throw new Twig_Error_Runtime(sprintf('An exception has been thrown during the rendering of a template ("%s").', $e->getMessage()), -1, $this->getSourceContext(), $e);
        }
    }

    /**
     * Auto-generated method to display the template with the given context.
```
**contact form**
```yml
contact:
    submission:
        ajax: false                   # Use AJAX for form submission and handling
    notification:
        enabled: true
        debug: false
        debug_address: name@example.com # Email address used when debug mode is enabled
        debug_smtp: true
        subject: Your message was submitted
        from_name: name                 # Email addresses and names can be either the
        from_email: email               # name of a field below or valid text.
        replyto_email: email            #
        replyto_name: name              # NOTE: Email addresses must be valid
        to_name: My Site                #
        to_email: noreply@example.com   #
    feedback:
        success: Message submission successful
        error: There are errors in the form, please fix before trying to resubmit
    fields:
        sent_on:
            type: hidden
            options:
                label: false
            event: 
                name: timestamp
                params:
                    format: '%F %T'
        tripdate:
            type: text
            options:
                required: true
                label: Zeildatum
                attr:
                    placeholder: Wanneer is uw beste zeildatum?
        amount:
            type: number
            options:
                label: Aantal deelnemers
                attr:
                    placeholder: Aantal deelnemers
        name:
            type: text
            options:
                required: true
                label: Naam
                attr:
                    placeholder: Naam
                constraints: [ NotBlank, { Length: { 'min': 3, 'max': 128 } } ]
        adress:
            type: text
            options:
                label: Adres
                attr:
                    placeholder: Adres
        phone:
            type: text
            options:
                label: Telefoon
                attr:
                    placeholder: Telefoon
        email:
            type: email
            options:
                required: true
                label: E-mail
                attr:
                    placeholder: E-mail
                constraints: [ NotBlank, Email ]
        tripschoice:
            type: choice
            options:
                required: true
                label: ContentType selection
                choices: content
                params:
                    contenttype: trips
                    label: title
                    value: slug
                    limit: 4
                    sort: title
                    order: DESC
        message:
            type: textarea
            options:
                required: true
                label: Heeft u nog vragen ?
                attr:
                    placeholder: Ik heb nog de volgende vragen en / of ideeën
                    class: myclass
        submit:
            type: submit
            options:
                label: madraque boeken
                attr:
                    class: button primary
```
