### ISSUE TITLE
[BUG] [BoltForms 4.1] Choice fields break form submission

### ISSUE THREAD

**Issue by nestordedios** [bolt/boltforms#186]
Hi there again!

Still having some trouble with BoltForms 4.1 😅 but getting closer to succeed 😄  .

Now, Form submission is throwing a `InternalProcessorException in DatabaseTable.php line 79:
An exception occurred saving submission to database table 'bolt_conference_registration'`

In my boltforms.bolt.yml I have a choice field that displays as a checkbox `expanded: true` and `multiple: true`. When the checkbox is checked and the form is submitted the value is passed as an array to be stored in the database. It seems that submited arrays are not are not being converted to a String or other data-type.

Here seems to go wrong when trying to insert() `$saveData[]` into the database. 
https://github.com/bolt/boltforms/blob/4.1/src/Submission/Handler/DatabaseTable.php#L77

This is part of my boltforms.bolt.yml
```
register:
  database:
    table: bolt_conference_registration    # Specific database table to write to
  fields:
     ...
    city_country:
      type: text
      options:
        required: true
        label: City and Country
        attr:
          placeholder: "Name of City, Country"
    conference_dinner:
      type: choice
      options:
        required: false
        label: ' '
        choices:
            'I wish to register for Conference Dinner on Monday, 22 January 2018 (€ 100)': 'I wish to register for Conference Dinner on Monday, 22 January 2018 (€ 100)*'
        expanded: true
        multiple: true
    submit:
      type: submit
      options:
        label: Register
```

Is this a bug or am I setting something wrong in the config of the form?

Details
-------

 - Relevant Bolt Version: [ 3.3 ]
 - Install type: [ Composer install ]
 - PHP version: [ 5.6 ]
 - Used web server: [ Apache  ]
