### ISSUE TITLE
[BUG] Form notification 'from_name' option doesn't accept array 

### ISSUE THREAD

**Issue by nestordedios** [bolt/boltforms#203]
Hi! 

I just bumped into what seems to be a bug. I'm using BoltForms 4.1.13. I want it to be possible to set the value of the `from_name:` notification option to a 'name' + 'lastname' field.

To reproduce this error I used the default contact Form in `boltforms.bolt.yml`. Added a new text field called `lastname`.

```
...
fields:
        ...
        lastname:
            type: text
            options:
                required: true
                label: Lastname
                attr:
                    placeholder: Your lastname...
                constraints: [ NotBlank, { Length: { 'min': 3, 'max': 128 } } ]
        ...
```
 and in the notification settings of the form I used the configuration below:
```
contact:
    submission:
        ajax: false                   # Use AJAX for form submission and handling
    notification:
        enabled: true
        debug: false
        debug_address: nestor@twokings.nl       # Email address used when debug mode is enabled
        debug_smtp: true                        #
        subject: Your message was submitted     #
        from_name: [ name, lastname ]           # Email addresses and names can be either the
        from_email: email                       # name of a field below or valid text.
        replyto_email: email                    #
        replyto_name: name                      # NOTE: Email addresses must be valid
        to_name: My Site                        #
        to_email: nestor@twokings.nl            #
```
I haven't tested it but it might be the same for the `replyto_name` option if it happened to be `replyto_name: [ name, lastname ]`.
 
A screenshot of the error I got:
![1 3_error_trace](https://user-images.githubusercontent.com/6607455/32053248-0aec9baa-ba5b-11e7-8f00-e2ac32c71bc3.png)

The expect result would have been a successfully submitted form and a sent notification email received where the `From:` email header would be set with the value of the name and the lastname fields.  

#### Details
Relevant Bolt Version: [ 3.3 ]
Install type: [ Composer install ]
PHP version: [ 5.6 ]
Used web server: [ Apache ]
