### ISSUE TITLE
[Feature Request] fieldsets support

### ISSUE THREAD

**Issue by jadwigo** [bolt/boltforms#204]
I've ran into the same problem multiple times (and other have too: #52) - which is grouping of form elements is not easy with BoltForms.

In HTML you're supposed to use `<fieldset>` elements for that. Unfornunately Symfony Forms does not support that.

I would like support for  `<fieldset>` elements in BoltForms, and I propose a syntax that looks like this:

```yml
## Example 1
#
# Contact Form
contact:
    submission:
        ajax: false                   # Use AJAX for form submission and handling
    notification:
        enabled: true
        debug: false
        debug_address: name@example.com # Email address used when debug mode is enabled
        debug_smtp: true
        subject: Your message was submitted
        from_name: name                 # Email addresses and names can be either the
        from_email: email               # name of a field below or valid text.
        replyto_email: email            #
        replyto_name: name              # NOTE: Email addresses must be valid
        to_name: My Site                #
        to_email: noreply@example.com   #
    feedback:
        success: Message submission successful
        error: There are errors in the form, please fix before trying to resubmit
    fieldsets:
        personal:
            label: Personal Information
            attr:
                class: form-inline
        message:
            label: Message information
        footer:
            label: false
            attr:
                class: footer-class
    fields:
        name:
            type: text
            fieldset: personal
            options:
                required: true
                label: Name
                attr:
                    placeholder: Your name...
                constraints: [ NotBlank, { Length: { 'min': 3, 'max': 128 } } ]
        email:
            type: email
            fieldset: personal
            options:
                required: true
                label: Email address
                attr:
                    placeholder: Your email...
                constraints: [ NotBlank, Email ]
        message:
            type: textarea
            fieldset: message
            options:
                required: true
                label: Your message
                attr:
                    placeholder: Your message...
                    class: myclass
        needreply:
            type: choice
            fieldset: footer
            options:
                required: false
                label: Do you want us to contact you back?
                choices: { 'Yes': 'yes', 'No': 'no' }
                multiple: false
        submit:
            type: submit
            fieldset: false
            options:
                label: Submit my message »
                attr:
                    class: button primary
```
