### ISSUE TITLE
[Feature Request] Prefix and Suffix elements

### ISSUE THREAD

**Issue by jadwigo** [bolt/boltforms#205]
Often when I create forms I want to add extra explanations to certain fields. (And I'm not the only one - #52 )

I would like to have `prefix`, `postfix` options.. and a `type: markup` field.

```yml
## Example 1
#
# Contact Form
contact:
    submission:
        ajax: false                   # Use AJAX for form submission and handling
    notification:
        enabled: true
        debug: false
        debug_address: name@example.com # Email address used when debug mode is enabled
        debug_smtp: true
        subject: Your message was submitted
        from_name: name                 # Email addresses and names can be either the
        from_email: email               # name of a field below or valid text.
        replyto_email: email            #
        replyto_name: name              # NOTE: Email addresses must be valid
        to_name: My Site                #
        to_email: noreply@example.com   #
    feedback:
        success: Message submission successful
        error: There are errors in the form, please fix before trying to resubmit
    fields:
        name:
            type: text
            options:
                required: true
                label: Name
                prefix: "<p>What should we call you, any psudonym is OK with us.</p>"
                attr:
                    placeholder: Your name...
                constraints: [ NotBlank, { Length: { 'min': 3, 'max': 128 } } ]
        email:
            type: email
            options:
                required: true
                label: Email address
                suffix: "<p>Please take extra care, often typo's like 'example@gmail.con' will mean the email will never reach you.</p>"
                attr:
                    placeholder: Your email...
                constraints: [ NotBlank, Email ]
        something_something:
            type: markup
            value: "<hr><div><p>This will not create a form element.. it will only show you whatever is in the 'value' of this field.</p></div>" 
        message:
            type: textarea
            options:
                required: true
                label: Your message
                attr:
                    placeholder: Your message...
                    class: myclass
        needreply:
            type: choice
            options:
                required: false
                label: Do you want us to contact you back?
                choices: { 'Yes': 'yes', 'No': 'no' }
                multiple: false
        submit:
            type: submit
            options:
                label: Submit my message »
                attr:
                    class: button primary
```
