### ISSUE TITLE
File upload is not sending/uploading files with the request

### ISSUE THREAD

**Issue by fvanhove** [bolt/boltforms#220]
Hello, 

as mentioned in the summary, bolt forms is not sending the files when submitting the request. 
Below is the configuration i use: 

```
uploads:
    enabled: true   
```

```
apply:
    submission:
        ajax: true                   
    notification:
        enabled: true
        attach_files: true
        from_name: <filled in>
        from_email: <filled in>         
        to_name: <filled in>
        to_email: <filled in>
    uploads:
        enabled: true 
```

```
upload:
     type: file
     options:
         required: true
         label: Your resume
```

Additional information: 

- The emails are sent using Spark post
- Bolt version: 3.4.0
- Bold forms version: v4.1.14
- I am using a blank .txt for testing

I am receiving the emails correctly, except for the fact the file is never uploaded. 
This also does not work when disabling attach_files.

**Comment by jadwigo** [comment]
Did you also setup the file settings in the beginning of the config.yml?:
```yml
uploads:
    enabled: true                               
    base_directory: /full/path/for/uploaded/files/
    filename_handling: suffix 

```

**Comment by fvanhove** [comment]
Hello, 

Yes, this is set to the following testing path
```
uploads:
    enabled: true
    base_directory: /files/attachments
    filename_handling: suffix
```
If i'm correct this should point to public/files/attachments which is a writable directory
