### ISSUE TITLE
Regex in constraints

### ISSUE THREAD

**Issue by tricksel** [bolt/boltforms#231]
Is it possible to add a regex to the constraints of a field? If so, how? I couldn't find it in the docs.

**Comment by tricksel** [comment]
Anyone?

**Comment by zomars** [comment]
I think your'e looking for the [Symfony Forms Validation](https://symfony.com/doc/3.4/reference/constraints/Regex.html).

**Comment by rossriley** [comment]
Specifically to implement it you need to configure your field something like this:

```
    fields:
        name:
            type: text
            options:
                required: true
                label: Name
                attr:
                    placeholder: 'Your name...'
                constraints:
                    - Regex:
                        pattern: "/^[a-zA-Z\s]$/"
```

Boltforms will take any Symfony Forms constraint, some like `NotBlank` or `Email` don't have any parameters, if needed the parameters can be configured like `pattern` in this example.
