### ISSUE TITLE
ReCaptcha doesn't accept custom config

### ISSUE THREAD

**Issue by xphoenyx** [bolt/boltforms#232]
I'm using BoltForms plugin to build a simple contact form with custom view. The building process was pretty straightforward and did not cause any problems (as there is already a pre-set config for contact form by default) until I faced the need to add Google ReCaptcha. No matter what is set in my `boltforms.bolt.yml` config file, the Twig `dump()` function prints the same result for the `recaptcha` value:

```
"enabled" => false
"label" => "Please enter the CAPTCHA text to prove you're a human"
"public_key" => ""
"theme" => "clean"
"type" => "v2"
"error_message" => "The CAPTCHA wasn't entered correctly. Please try again."
"badge_location" => "bottomright"
"error_codes" => null
"valid" => true
```

According to settings in my `boltforms.bolt.yml` config, almost all values should be actually different.

Yes, I followed the [BoltForms documentation](https://bolt.github.io/boltforms/) and yes, I've checked my code for any coincidences (I thaught maybe there is another configuration overwriting mine). Neither helped.

Here is my view with form (I'm using Translate and Labels plugins to translate some stuff):

```
{% import templates.recaptcha as spambot %}

{% if messages.error and app.request.get('contact') %}
    {% for error in messages.error %}
        <div class="alert alert-danger">
		  	{{ error }}
		</div>
    {% endfor %}
{% endif %}

{% if messages.info and app.request.get('contact') %}
    {% for info in messages.info %}
        <div class="alert alert-success">
		  	{{ info }}
		</div>
    {% endfor %}
{% endif %}

{{ form_start(form) }}

	{{ dump(recaptcha) }}

	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12"> 
		<div class="form-group">
			<label class=" control-label" for="name">{{ l("Name") }}:</label>
			{{ form_widget(form['name'], { 'attr': {'class': 'form-control'} }) }}
		</div>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<div class="form-group">
			<label class=" control-label" for="email">{{ l("E-mail") }}:</label>
			{{ form_widget(form['email'], { 'attr': {'class': 'form-control'} }) }}
		</div>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<div class="form-group">
			<label class=" control-label" for="phone">{{ l("Phone") }}:</label>
			{{ form_widget(form['phone'], { 'attr': {'class': 'form-control'} }) }}
		</div>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<div class="form-group">
			<label class=" control-label" for="subject">{{ l("Subject") }}:</label>
			{{ form_widget(form['subject'], { 'attr': {'class': 'form-control'} }) }}
		</div>
	</div>
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
		<div class="form-group">
			<label class=" control-label" for="textarea">{{ l("Message") }}:</label>
			{{ form_widget(form['message'], { 'attr': {'class': 'form-control', 'rows': 6} }) }}
		</div>
	</div>

	{% if form._token is defined %}
        {{ form_row(form._token) }}
    {% endif %}

    {{ spambot.recaptcha(recaptcha) }}

	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
		<div class="form-group">
			{{ form_widget(form['submit'], { 'attr': {'class': 'btn btn-default'}, 'label': l("Send") }) }}
		</div>
	</div>

{{ form_end(form) }}		
```

Versions:
bolt/bolt: v3.4.6
bolt/boltforms: v4.1.14

**Comment by jadwigo** [comment]
What are the settings (without the actual passwords and keys) for your recaptcha config in `boltforms.bolt.yml` ?

According to the fragments you showed, recaptcha is actually disabled.

**Comment by xphoenyx** [comment]
HI @jadwigo, thank you for the reply. Here are the settings from my `boltforms.bolt.yml`:

```
recaptcha:
        enabled: true
        label: "Palun sisestage kontrollkood"
        public_key: 'ABCDEF123456'
        private_key: 'ABCDEF123456'
        error_message: "Kontrollkood on vale. Plaun sisestage kontrollkood uuesti."
        theme: clean
        type: invisible
```

**Comment by jadwigo** [comment]
Does the form you use have the individual recaptcha disabled? https://bolt.github.io/boltforms/recaptcha.html#disabling-recaptcha-on-some-forms

**Comment by jadwigo** [comment]
Sorry for the late reply.

You have set the recaptcha config in the configuration for a specific form, it should be a top level configuration item in your `boltforms.bolt.yml` file. See https://bolt.github.io/boltforms/recaptcha.html

```yml
recaptcha:
    enabled: true
    label: "Palun sisestage kontrollkood"
    public_key: 'ABCDEF123456'
    private_key: 'ABCDEF123456'
    error_message: "Kontrollkood on vale. Plaun sisestage kontrollkood uuesti."
    theme: clean
    type: invisible

contact:
    templates:
        form: partials/_contactForm.twig
        email: partials/_email.twig
    submission:
        ajax: false
    notification:
        enabled: true
        debug: false
        debug_address: address@example.com
        debug_smtp: true
        subject: "Uus sõnum" 
        from_name: Project
        from_email: bot@example.com
        replyto_email: info@example.com
        replyto_name: Project
        to_name: Test
        to_email: address@example.com
    feedback:
        success: "Aitäh sõnumi eest! Vastame Teile esimesel võimalusel"
        error: "Palun kontrollige üle täidetud andmed"
    fields:
        name:
            type: text
            options:
                required: true
                constraints: [ NotBlank, { Length: { 'min': 3, 'max': 128 } } ]
        email:
            type: email
            options:
                required: true
                constraints: [ NotBlank, Email ]
        phone:
            type: text
            options:
                required: false
                constraints: [ NotBlank, { Length: { 'min': 6, 'max': 15 } } ]
        subject:
            type: text
            options:
                required: true
                constraints: [ NotBlank, { Length: { 'min': 3, 'max': 30 } } ]
        message:
            type: textarea
            options:
                required: true
        submit:
            type: submit
```

You can only use the `recaptcha` key insite of a form configuration if you want to disable the recaptcha for that single form. ( https://bolt.github.io/boltforms/recaptcha.html#disabling-recaptcha-on-some-forms )
