### ISSUE TITLE
[BUG] Image upload with save to contenttype doesn't work

### ISSUE THREAD

**Issue by Matthewbeck75** [bolt/boltforms#248]
Attempting to save an uploaded image to a contenttype within Bolt Forms is not working. This was brought up in issue #79 but since the code has been rewritten for version 4, it seems as though this bug has resurfaced. 

The image upload itself is working, and text based content is correctly saving to the contenttype. 

Details
-------

 - Bolt Version: [ 3.4.8 ]
 - Boltforms Version: [ 4.2.1 ]
 - Install type: [ Zip/tarball install  ]
 - PHP version: [  7.0 ]
 - Used web server: [  Nginx (1.10) Ubuntu (16.04.1) ]

Reproduction
------------

### Bug summary

Image uploads will not save to a contenttype. This happens no matter where the files are set to save, or if filename_handling is set to prefix or keep.

### Specifics

There are no error messages.

### Config

boltforms.bolt.yml:

```
imageform:
    submission:
        ajax: true                   
    database:
        contenttype: 
            name: imageupload
            field_map:
                answer: 'answer'
                image: 'image'
        fields:
            image:
                type: image
    feedback:
        success: Success!
        error: Looks like you missed something!

    fields:
        answer:
            type: text
            options:
                required: true
                attr:
                    placeholder: Answer
                constraints: [ NotBlank ]
        image:
            type: file
            options:
                required: false

        submit:
            type: submit
            options:
                label: Make My Umm!
                attr:
                  class: submit none
```

in contenttypes.yml:

```
imageupload:
    name: imageupload
    singular_name: imageupload
    viewless: true
    searchable: false
    show_in_menu: "Submissions"
    default_status: held
    show_on_dashboard: false
    fields:          
        answer:
            type: text
            label: Answer
            group: "Name"
        drawing:
            type: image
            label: Drawing
            group: "Name"

```
### Expected result

Contenttype imageform to be populated with the location of the image within its image field.

### Actual result

Only the text based field is currently populating.
