### ISSUE TITLE
[BUG] Unable to save uploads: Twig_Error_Runtime 

### ISSUE THREAD

**Issue by peterboorsma** [bolt/boltforms#273]
After updating a website to the latest Bolt/Boltforms versions an error occurs when uploads are enabled and a form is submitted.
Form submissions are being saved in the Bolt db and sent by mail.

When I disable uploads, the form submission is being stored in the db nicely and mails are being sent normally.
My base_dir is correct
My contenttypes are fine
My Boltform config is good
I built and tested it locally and everything works fine, but not on the webserver.

The same form works normally with older versions on the same server (Bolt 3.2.20 / Boltforms 3.1.0)

```
uploads:
  enabled: true 
  base_directory: /var/www/vhosts/staging.mydomain.nl/formuploads/
  filename_handling: suffix
  management_controller: true         
```         

Enabling the uploads breaks stuff:

![schermafbeelding 2019-01-08 om 19 35 51](https://user-images.githubusercontent.com/2750653/50851301-b8deea80-137c-11e9-9b02-662705fac7a2.png)
![schermafbeelding 2019-01-08 om 19 36 34](https://user-images.githubusercontent.com/2750653/50851480-41f62180-137d-11e9-8778-9d1d91326406.png)

I hope someone can explain what goes wrong here.

Bolt version: 3.6.3
Boltforms version: 4.2.5
PHP version: 7.2.13
Server: nginx/1.11.10 , 5.5.60-MariaDB - MariaDB Server, libmysql - mysqlnd 5.0.11

**Comment by bobdenotter** [comment]
Ok, here's my guess.. It's not breaking because of the upload, it's breaking on one of the fields in the contenttype.. My initial guess would be `upload` because of the `[]` there.. How's that field defined in the contenttype.yml?

**Comment by peterboorsma** [comment]
Like this:

```
        upload:
            type: text
            class: narrow
            variant: inline
```

And in the db this:
![schermafbeelding 2019-01-09 om 11 57 41](https://user-images.githubusercontent.com/2750653/50895355-2edb6400-1406-11e9-8425-5265d5ef8e05.png)
