### ISSUE TITLE
[Feature request] Ability to send a download link instead of attaching files

### ISSUE THREAD

**Issue by SahAssar** [bolt/boltforms#44]
Hey, 

I took this up on IRC, but thought I'd mention it here too.

I'd love to be able to send a download link to a file instead of attaching it to the email, which would cover scenarios like when attachments have a greater risk of getting caught in spam filter and when files are too large for attachments.

**Comment by GawainLynch** [comment]
So if you had a form with `attach_files: false`

```yaml
myform:
  notification:
    enabled: true
    attach_files: false
```

Then make the field a download link instead?
