### ISSUE TITLE
Mailoptions documentation

### ISSUE THREAD

**Issue by peterboorsma** [bolt/boltforms#55]
Is there any documentation about the mailoption settings?

```
mailoptions:
    transport: smtp
    spool: true
    host:
    username: 
    password: 
    port: 25
    encryption: null
    auth_mode: null
    senderMail: null
    senderName: null

```

I'm still trying to get BoltForms to work ... What are the options for auth_mode for instance?
