### ISSUE TITLE
how to get form data in subject template

### ISSUE THREAD

**Issue by everyx** [bolt/boltforms#69]
In `boltforms.bolt.yml`

```yml
  templates:
   form: partials/_contact_form.twig
   email: partials/_contactform_email.twig
   subject: partials/_contactform_email_subject.twig
```

in subject template file

```twig
{% spaceless %}
{{ subject }} from {{ name }} - jdhandbagfactory.com
{% endspaceless %}
```

but the subject of the email is missing the value "name", how can i get the name value from the form data in subject template?
