### ISSUE TITLE
Multiple emails

### ISSUE THREAD

**Issue by tameroski** [bolt/boltforms#75]
Hi,
Is it possible to use multiple email adresses for the to_email, cc_email and bcc_email fields ?
I tried with an yml array like this
`cc_email: ['bar@foo.com', 'foo@bar.org']`
But that doesn't seam to work (and it does with a single value).

**Comment by GawainLynch** [comment]
Not currently.

**Comment by GawainLynch** [comment]
Just having a look back over all of this… apart from a rather abrupt response on my part :disappointed: I am not really sure the best way to implement this as there needs to be a matching `name` field so if one was missing… which one does what?

Might go back to ruminating on this one in lieu of suggestions

**Comment by Puddingboy** [comment]
I want to offer a suggestion to this subject:

We have cases where we need to shape different emails for different recipants. 
For example an email to the user that shows what has been sent with a message to let them know we will look into it in a short while. 
The main email would go to the company containing the mail itself and perhaps a few extra bits of user information.
In this scenario 2 different templates to point to for each user would be usefull.

```
recipents:
    admin: "admin@domain.com"
        from: "domain/form/user"
        email: email_field/some
        to: "sales/info/feedback@domain.com"
        subject: "question/suggestion/subscription/whatever" / "admin_subject_template.twig"
        template: "admin_mailtemplate.twig"
    user: 
        from: "domain/company name"
        email: noreply/whatever@domain.com
        to: name_field
        subject: "your [insert] has been sent" / "user_subject_template.twig"
        template: "user_mailtemplate.twig"
```

Another way would be to just point to templates where variables could be used:

```
admin: "admin_email_template.twig"
user: "user_email_template.twig"
```

Just to throw it in there. Feel free to offer input. I may revise this over time.
