### ISSUE TITLE
file/image uploads with save to contenttype don't work but save to table works

### ISSUE THREAD

**Issue by jadwigo** [bolt/boltforms#79]
If I have a file upload field in a boltform and I save the form to a contenttype the files are uploaded but the image field in the content type will not be populated.

```
  database:
    contenttype: agenda
  fields:
    image:
      type: file
```

If I do the same but save the form to a bolt table - that is actually the same as the bolt contenttype - the image fields are populated

```
  database:
    table: bolt_agenda
  fields:
    image:
      type: file
```
