### ISSUE TITLE
The fields replyto_name and replyto_email doesn't seem to work

### ISSUE THREAD

**Issue by superferenabled** [bolt/boltforms#84]
Hi, I am using boltforms in a simple contact form and I let the fieldnames configured as is specified in the default configuration:

```
    replyto_name: name                    # A field name, specified in the fields: section below
    replyto_email: email                     # A field name, specified in the fields: section below
```

obviously those field names exists in the fields configuration:

```
fields:
    name:
      type: text
      options:
        required: true
        label: Nombre
        attr:
          placeholder: Name *
        constraints: [ NotBlank, {Length: {'min': 3}} ]
    email:
      type: email
      options:
        required: true
        label: Email address
        attr:
          placeholder: Email *
        constraints: [ NotBlank, Email ]
```

then I do the following:  **write a test email and** -> **get that email in my inbox** -> **click the button reply**

this doesn't show the values I wrote in the fields of the test email.  Am I missing something??
